### ISSUE TITLE
Develop CashierMachine

### ISSUE THREAD

**Issue by Xrayya** [Xrayya/java-cli-pbpu#6]

**Comment by putubhanuartha** [comment]
Buat method removeOrder itu aku ambil orderId (UUID) nya dari object order (Order)  ya?
Kalau di editOrder itu soalnya buat nyarinya itu pake nilai parameter orderId (UUID) langsung,
jadi biar konsisten, yang removeOrder ga pake langsung aja parameternya orderId (UUID) ?

**Comment by Xrayya** [comment]
List itu support hapus menu yang sesuai kok, jadi langsung hapus aja pake objeknya itu

**Comment by Xrayya** [comment]
Eh, tp itu kayaknya harus implement comparable nya deh, tar deh, habis ini aku tambahin
